project/cliente/urls.py
from django.urls import path
from . import views

app_name = 'cliente'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('cliente/create/', views.cliente_create, name="cliente_create"),
    path('cliente/nacionalidad/create/', views.nacionalidad_create, name="nacionalidad_create"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('producto/', include("producto.urls")),
    path('cliente/', include("cliente.urls")),
]

project/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name = "home"),
]

project/producto/urls.py
from django.urls import path
from . import views

app_name = 'producto'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('producto/create/', views.producto_create, name="producto_create"),
    path('productocategoria/create/', views.productocategoria_create, name="productocategoria_create"),
]

project/cliente/models.py
from django.db import models

class Nacionalidad(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nombre}"

class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.IntegerField()
    mail = models.CharField(max_length=50, blank=True, null=True)
    direccion = models.CharField(max_length=100, blank=True, null=True)
    nacionalidad_id =models.ForeignKey(Nacionalidad, on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

project/producto/models.py
from django.db import models

class ProductoCategoria(models.Model):

    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200)
    precio = models.IntegerField()
    categoria_id = models.ForeignKey(ProductoCategoria, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.nombre} {self.precio}"

project/cliente/forms.py
from django import forms
from . import models

class NacionalidadForm(forms.ModelForm):
    class Meta:
        model = models.Nacionalidad
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre"}),
        }

class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre"}),
            "apellido": forms.TextInput(attrs={"class": "form-control", "placeholder": "Apellido"}),
            "nacionalidad": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nacionalidad"}),
            "direccion": forms.TextInput(attrs={"class": "form-control", "placeholder": "Dirección"}),
            # "telefono": forms.IntegerField(attrs={"class": "form-control", "placeholder": "Teléfono"}),
            "mail": forms.TextInput(attrs={"class": "form-control", "placeholder": "Mail"}),
        }

project/producto/forms.py
from django import forms
from . import models

class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del producto"}),
            "descripcion": forms.Textarea(attrs={"class": "form-control", "placeholder": "Descripción del producto"}),
        }


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del producto"}),
        }

project/cliente/views.py
from django.shortcuts import render, redirect
from . import models, forms

def home(request):
    consulta_cliente = models.Cliente.objects.all()
    context = {"clientes": consulta_cliente}
    return render(request, "cliente/index.html", context)

def nacionalidad_create(request):
        if request.method == "POST":
            form = forms.NacionalidadForm(request.POST)
            if form.is_valid:
                form.save()
                return redirect("cliente:home")
        else:  
            form = forms.NacionalidadForm()
        
        return render(request, "cliente/nacionalidad_create.html", context={"form": form})

def cliente_create(request):
        if request.method == "POST":
            form = forms.ClienteForm(request.POST)
            if form.is_valid:
                form.save()
                return redirect("cliente:home")
        else:  
            form = forms.ClienteForm()
        
        return render(request, "cliente/cliente_create.html", context={"form": form})

project/core/views.py
from django.shortcuts import render
from . import models

def home(request):
    return render(request, "core/index.html")

project/producto/views.py
from django.shortcuts import render, redirect
from . import models, forms

def home(request):
    consulta_producto = models.Producto.objects.all()
    context = {"productos": consulta_producto}
    return render(request, "producto/index.html", context)

def producto_create(request):
    if request.method == "POST":
        form = forms.ProductoForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("producto:home")
    else:  
        form = forms.ProductoForm()
    
    return render(request, "producto/producto_create.html", context={"form": form})

def productocategoria_create(request):
    if request.method == "POST":
        form = forms.ProductoCategoriaForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("producto:home")
    else:  
        form = forms.ProductoCategoriaForm()
    
    return render(request, "producto/productocategoria_create.html", context={"form": form})

project/cliente/templates/cliente/cliente_create.html
{% extends 'core/base.html' %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center border rounded shadow p-3 mt-3">
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{% url 'cliente:home' %}" class="btn btn-primary">Volver</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contenido %}

project/cliente/templates/cliente/components/card.html
<div class="container py-5">
    {% for cliente in clientes %}
    <div class="row mb-4">
        <div class="col">
            <div class="card bg-light border-0 shadow">
                <div class="card-body">
                    <h3 class="card-title text-dark fw-bold">{{ cliente.apellido }} {{cliente.nombre}}</h3>
                    <hr>
                    <p class="card-text text-dark fw-bold">Nacionalidad: {{cliente.nacionalidad_id}}</p>
                    <p class="card-text text-dark fw-bold">Dirección: {{cliente.direccion}}</p>
                    <p class="card-text text-dark fw-bold">Teléfono: {{cliente.telefono}}</p>
                    <p class="card-text text-dark">Mail: {{cliente.mail}}</p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

project/cliente/templates/cliente/components/options.html
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <a href="{% url 'cliente:cliente_create' %}" class="btn btn-primary btn-lg btn-block">Cargar Cliente</a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'cliente:nacionalidad_create' %}" class="btn btn-primary btn-lg btn-block">Cargar Nacionalidad</a>
        </div>
    </div>
</div>

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% include 'core/components/titulo.html' with titulo="Clientes" %}
{% endblock titulo %}

{% block contenido %}
    {% include 'cliente/components/options.html' %}
    {% include 'cliente/components/card.html' %}
{% endblock contenido %}

project/cliente/templates/cliente/nacionalidad_create.html
{% extends 'core/base.html' %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center border rounded shadow p-3 mt-3">
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{% url 'cliente:home' %}" class="btn btn-primary">Volver</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Technology CBA</title>

        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include 'core/components/navbar.html' %}

        {% block titulo %}
        {% endblock titulo %}
        
        {% block contenido %}
        {% endblock contenido %}
        
        {% include 'core/components/footer.html' %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/components/banner.html
{% load static %}

<div  id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'core/img/banner_1.webp' %}" class="d-block w-100" alt="computadora gamer">
      </div>
      <div class="carousel-item">
        <img src="{% static 'core/img/banner_2.webp' %}" class="d-block w-100" alt="mouse gamer">
      </div>
      <div class="carousel-item">
        <img src="{% static 'core/img/banner_3.webp' %}" class="d-block w-100" alt="micro amd">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

project/core/templates/core/components/footer.html
<footer class="py-3 bg-dark fixed-bottom mt-4">
    <div class="container">
        <p class="m-0 text-center text-white">Technology CBA</p>
    </div>
</footer>

project/core/templates/core/components/navbar.html
<nav class="navbar py-3   navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Technology CBA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'producto:home' %}">Productos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'cliente:home' %}">Clientes</a></li>
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/components/titulo.html
<div class="row align-items-center my-3 mx-5 rounded border" style="background-color: #7cf5f5;">
    <h1 class="text-dark px-5">
        {{ titulo }}
    </h1>
</div>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
{% include 'core/components/banner.html' %}

<section class="mb-5 ">
    <div class="container">
        <div class="row align-items-center mt-3 ">
            <div class="col-md-6">
                <div class="card p-4 mt-4" style="background-color: #f8f9fa;">
                    <h2>Technology CBA</h2>
                    <p>La meca tecnológica de Córdoba, ofrece una gama completa de productos y servicios informáticos. Desde hardware de última generación hasta software innovador, brindan soluciones integrales para todos los clientes. Con expertos en tecnología y un servicio al cliente excepcional, son líderes indiscutibles en el mercado.</p>
                </div>
            </div>
            <div class="col-md-6 mt-4">
                <img src="{% static 'core/img/pc_gamer.webp' %}" alt="PC Gamer" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row align-items-center mt-3 ">
            <div class="col-md-6 mt-4 d-flex align-items-center justify-content-center mb-5 ">
                <img src="{% static 'core/img/informatica.webp' %}" alt="PC Gamer" class="img-fluid h-100 w-100">
            </div>
            
            <div class="col-md-6">
                <div class="card p-4 mt-4" style="background-color: #f8f9fa;">
                    <h2>El mejor asesoramiento</h2>
                    <p>Technology CBA sobresale por su asesoramiento experto en tecnología. Con un equipo altamente capacitado, brindan soluciones personalizadas y orientación integral en hardware, software y servicios informáticos, asegurando la satisfacción y el éxito de cada cliente.</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock contenido %}

        

project/producto/templates/producto/components/cards.html
<div class="container py-5">
    <div class="row row-cols-1 row-cols-md-3 justify-content-center">
        {% for producto in productos %}
        <div class="col mb-4">
            <div class="card h-100 bg-light border-0 shadow">
                <div class="card-body">
                    <h3 class="card-title text-dark fw-bold">{{producto.nombre}}</h3>
                    <p class="card-text text-dark">{{producto.descripcion}}</p>
                    <h5 class="card-text text-dark fw-bold">${{producto.precio}}</h5>
                </div>
                <div class="card-footer border-0 bg-transparent d-flex justify-content-center">
                    <a class="btn btn-dark mb-1" href="https://wa.me/5493517010243">Info</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

project/producto/templates/producto/components/options.html
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <a href="{% url 'producto:producto_create' %}" class="btn btn-primary btn-lg btn-block">Cargar Producto</a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'producto:productocategoria_create' %}" class="btn btn-primary btn-lg btn-block">Cargar Categoría</a>
        </div>
    </div>
</div>

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% include 'core/components/titulo.html' with titulo="Productos" %}
{% endblock titulo %}

{% block contenido %}

{% include 'producto/components/options.html' %}
{% include 'producto/components/cards.html' %}

{% endblock contenido %}

project/producto/templates/producto/producto_create.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% include 'core/components/titulo.html' with titulo="Carga de Productos" %}
{% endblock titulo %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center border rounded shadow p-3 mt-3">
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{% url 'producto:home' %}" class="btn btn-primary">Volver</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contenido %}

project/producto/templates/producto/productocategoria_create.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% include 'core/components/titulo.html' with titulo="Carga de Categoria" %}
{% endblock titulo %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center border rounded shadow p-3 mt-3">
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{% url 'producto:home' %}" class="btn btn-primary">Volver</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contenido %}